//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SicProyecto.Module.BusinessObjects.Chocoloat
{

    public partial class Parametros : XPObject
    {
        string fIndiceCuentaGastos;
        public string IndiceCuentaGastos
        {
            get { return fIndiceCuentaGastos; }
            set { SetPropertyValue<string>(nameof(IndiceCuentaGastos), ref fIndiceCuentaGastos, value); }
        }
        string fIndiceCuentaIngresos;
        public string IndiceCuentaIngresos
        {
            get { return fIndiceCuentaIngresos; }
            set { SetPropertyValue<string>(nameof(IndiceCuentaIngresos), ref fIndiceCuentaIngresos, value); }
        }
        CatalogoCuentas fCuentaPerdidaGanancia;
        public CatalogoCuentas CuentaPerdidaGanancia
        {
            get { return fCuentaPerdidaGanancia; }
            set { SetPropertyValue<CatalogoCuentas>(nameof(CuentaPerdidaGanancia), ref fCuentaPerdidaGanancia, value); }
        }
        [Association(@"EstadoDeResultadoReferencesParametros")]
        public XPCollection<EstadoDeResultado> EstadoDeResultadoes { get { return GetCollection<EstadoDeResultado>(nameof(EstadoDeResultadoes)); } }
    }

}
