//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SicProyecto.Module.BusinessObjects.Chocoloat
{

    public partial class PartidaContableDetalle : XPObject
    {
        PartidaContable fPartidaContable;
        [Association(@"PartidaContableDetalleReferencesPartidaContable")]
        public PartidaContable PartidaContable
        {
            get { return fPartidaContable; }
            set { SetPropertyValue<PartidaContable>(nameof(PartidaContable), ref fPartidaContable, value); }
        }
        CatalogoCuentas fCuentaContable;
        public CatalogoCuentas CuentaContable
        {
            get { return fCuentaContable; }
            set { SetPropertyValue<CatalogoCuentas>(nameof(CuentaContable), ref fCuentaContable, value); }
        }
        string fConcepto;
        public string Concepto
        {
            get { return fConcepto; }
            set { SetPropertyValue<string>(nameof(Concepto), ref fConcepto, value); }
        }
        decimal fCargo;
        public decimal Cargo
        {
            get { return fCargo; }
            set { SetPropertyValue<decimal>(nameof(Cargo), ref fCargo, value); }
        }
        decimal fAbono;
        public decimal Abono
        {
            get { return fAbono; }
            set { SetPropertyValue<decimal>(nameof(Abono), ref fAbono, value); }
        }
    }

}
