//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SicProyecto.Module.BusinessObjects.Chocoloat
{

    public partial class PartidaContable : XPObject
    {
        int fNumero;
        public int Numero
        {
            get { return fNumero; }
            set { SetPropertyValue<int>(nameof(Numero), ref fNumero, value); }
        }
        long fNumeroMayorizacion;
        public long NumeroMayorizacion
        {
            get { return fNumeroMayorizacion; }
            set { SetPropertyValue<long>(nameof(NumeroMayorizacion), ref fNumeroMayorizacion, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        Module.BusinessObjects.SicEnum.EstadoPartidaContable fEstatus;
        public Module.BusinessObjects.SicEnum.EstadoPartidaContable Estatus
        {
            get { return fEstatus; }
            set { SetPropertyValue<Module.BusinessObjects.SicEnum.EstadoPartidaContable>(nameof(Estatus), ref fEstatus, value); }
        }
        TipoPartida fTipo;
        public TipoPartida Tipo
        {
            get { return fTipo; }
            set { SetPropertyValue<TipoPartida>(nameof(Tipo), ref fTipo, value); }
        }
        string fConcepto;
        public string Concepto
        {
            get { return fConcepto; }
            set { SetPropertyValue<string>(nameof(Concepto), ref fConcepto, value); }
        }
        decimal fTotalCargo;
        [DbType("(18,8)")]
        public decimal TotalCargo
        {
            get { return fTotalCargo; }
            set { SetPropertyValue<decimal>(nameof(TotalCargo), ref fTotalCargo, value); }
        }
        decimal fTotalAbono;
        [DbType("(18,8)")]
        public decimal TotalAbono
        {
            get { return fTotalAbono; }
            set { SetPropertyValue<decimal>(nameof(TotalAbono), ref fTotalAbono, value); }
        }
        string fPeriodo;
        public string Periodo
        {
            get { return fPeriodo; }
            set { SetPropertyValue<string>(nameof(Periodo), ref fPeriodo, value); }
        }
        long fNumeroReferencia;
        public long NumeroReferencia
        {
            get { return fNumeroReferencia; }
            set { SetPropertyValue<long>(nameof(NumeroReferencia), ref fNumeroReferencia, value); }
        }
        DateTime fFechaRegistro;
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        Module.BusinessObjects.SicEnum.TipoPartida fTipoPartida;
        public Module.BusinessObjects.SicEnum.TipoPartida TipoPartida
        {
            get { return fTipoPartida; }
            set { SetPropertyValue<Module.BusinessObjects.SicEnum.TipoPartida>(nameof(TipoPartida), ref fTipoPartida, value); }
        }
        [Association(@"PartidaContableDetalleReferencesPartidaContable")]
        public XPCollection<PartidaContableDetalle> PartidaContableDetalles { get { return GetCollection<PartidaContableDetalle>(nameof(PartidaContableDetalles)); } }
    }

}
