//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SicProyecto.Module.BusinessObjects.Chocoloat
{

    public partial class SaldoCuentas : XPObject
    {
        DateTime fFechaRegistro;
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        CatalogoCuentas fCuenta;
        public CatalogoCuentas Cuenta
        {
            get { return fCuenta; }
            set { SetPropertyValue<CatalogoCuentas>(nameof(Cuenta), ref fCuenta, value); }
        }
        decimal fSaldoInicial;
        public decimal SaldoInicial
        {
            get { return fSaldoInicial; }
            set { SetPropertyValue<decimal>(nameof(SaldoInicial), ref fSaldoInicial, value); }
        }
        decimal fCargo;
        public decimal Cargo
        {
            get { return fCargo; }
            set { SetPropertyValue<decimal>(nameof(Cargo), ref fCargo, value); }
        }
        decimal fAbono;
        public decimal Abono
        {
            get { return fAbono; }
            set { SetPropertyValue<decimal>(nameof(Abono), ref fAbono, value); }
        }
        decimal fSaldoFinal;
        public decimal SaldoFinal
        {
            get { return fSaldoFinal; }
            set { SetPropertyValue<decimal>(nameof(SaldoFinal), ref fSaldoFinal, value); }
        }
        SaldoCuentas fSaldoCuentaPadre;
        [Association(@"SaldoCuentasReferencesSaldoCuentas")]
        public SaldoCuentas SaldoCuentaPadre
        {
            get { return fSaldoCuentaPadre; }
            set { SetPropertyValue<SaldoCuentas>(nameof(SaldoCuentaPadre), ref fSaldoCuentaPadre, value); }
        }
        string fPeriodoContable;
        public string PeriodoContable
        {
            get { return fPeriodoContable; }
            set { SetPropertyValue<string>(nameof(PeriodoContable), ref fPeriodoContable, value); }
        }
        [Association(@"SaldoCuentasReferencesSaldoCuentas")]
        public XPCollection<SaldoCuentas> SaldoCuentasCollection { get { return GetCollection<SaldoCuentas>(nameof(SaldoCuentasCollection)); } }
    }

}
